### ISSUE TITLE
Compilation error with intel-mkl BLAS backend

### ISSUE THREAD

**Issue by relf** [relf/egobox#162]
Compilation with intel MKL BLAS backend fails

```bash
   Compiling intel-mkl-tool v0.3.2+mkl2020.1
   Compiling intel-mkl-src v0.7.0+mkl2020.1
The following warnings were emitted during compilation:

warning: intel-mkl-src@0.7.0+mkl2020.1: "Download Intel MKL archive into D:\rlafage\workspace\egobox\target\release\build\intel-mkl-src-5fe8678114faedaa\out"

error: failed to run custom build command for `intel-mkl-src v0.7.0+mkl2020.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\rlafage\workspace\egobox\target\release\build\intel-mkl-src-9ddd3d417f3b2fb5\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=MKL_STATIC_LP64_SEQ_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=MKL_STATIC_LP64_SEQ_STATIC
  cargo:rerun-if-env-changed=MKL_STATIC_LP64_SEQ_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=MKL_STATIC_LP64_SEQ_STATIC
  cargo:rerun-if-env-changed=MKL_STATIC_LP64_SEQ_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning="Download Intel MKL archive into D:\rlafage\workspace\egobox\target\release\build\intel-mkl-src-5fe8678114faedaa\out"

  --- stderr
  thread 'main' panicked at D:\rlafage\.cargo\registry\src\index.crates.io-6f17d22bba15001f\intel-mkl-tool-0.3.2+mkl2020.1\src\download.rs:38:28:
  called `Result::unwrap()` on an `Err` value: Error { description: "HTTP response code said error", code: 22, extra: Some("The requested URL returned error: 403") }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
     1: core::panicking::panic_fmt
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\result.rs:1654
     3: intel_mkl_tool::download::read_from_url
     4: __ImageBase
     5: std::rt::lang_start
     6: std::rt::lang_start
     7: __ImageBase
     8: std::rt::lang_start
     9: std::rt::lang_start_internal
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\rt.rs:148
    10: std::rt::lang_start
    11: main
    12: invoke_main
               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
    13: __scrt_common_main_seh
               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
    14: BaseThreadInitThunk
    15: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by relf** [comment]
depends on https://github.com/rust-ml/linfa/issues/353

**Comment by relf** [comment]
Fixed by #234
